=== SARDONYX-sard/serde-hkx/assets/havok_class_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Havok Class Information Schema",
  "description": "Schema for describing Havok Class Information in Json format.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the C++ class."
    },
    "parent": {
      "type": "string",
      "description": "Parent classes of the C++ class."
    },
    "parent_has_string": {
      "type": "boolean",
      "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
    },
    "version": {
      "type": "integer",
      "description": "Version of the class."
    },
    "signature": {
      "type": "string",
      "description": "Signature of the class."
    },
    "size_x86": {
      "type": "integer",
      "description": "Size of the class in 32-bit environment."
    },
    "size_x86_64": {
      "type": "integer",
      "description": "Size of the class in 64-bit environment."
    },
    "vtable": {
      "type": "boolean",
      "description": "Flag indicating if the class has a vtable."
    },
    "has_string": {
      "type": "boolean",
      "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
    },
    "enums": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the enum."
          },
          "vtype": {
            "type": "string",
            "enum": ["TYPE_ENUM", "TYPE_FLAGS"],
            "description": "Is this enum an `TYPE_ENUM` or a `TYPE_FLAGS`?"
          },
          "vsubtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64"
            ],
            "description": "The size of this enum when it is written to the binary; if it is `TYPE_VOID`, it means that the enum is not used and is unknown."
          },
          "flags": {
            "type": "string",
            "description": "Unknown flags . Always `00000000` in hk2010 version"
          },
          "enum_item": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of the enum item."
                },
                "value": {
                  "type": "integer",
                  "description": "Value of the enum item."
                }
              },
              "required": ["name", "value"]
            }
          }
        },
        "required": ["name", "vtype", "vsubtype", "flags", "enum_item"]
      },
      "description": "Enums associated with the class."
    },
    "members": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the C++ member."
          },
          "class_ref": {
            "type": "string",
            "description": "Name of the referenced class if `vtype` or `vsubtype` is `TYPE_POINTER` or `TYPE_STRUCT`."
          },
          "has_string": {
            "type": "boolean",
            "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
          },
          "ctype": {
            "type": "string",
            "description": "C data type of the member."
          },
          "vtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_BOOL",
              "TYPE_CHAR",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64",
              "TYPE_REAL",
              "TYPE_VECTOR4",
              "TYPE_QUATERNION",
              "TYPE_MATRIX3",
              "TYPE_ROTATION",
              "TYPE_QSTRANSFORM",
              "TYPE_MATRIX4",
              "TYPE_TRANSFORM",
              "TYPE_ZERO",
              "TYPE_POINTER",
              "TYPE_FUNCTIONPOINTER",
              "TYPE_ARRAY",
              "TYPE_INPLACEARRAY",
              "TYPE_ENUM",
              "TYPE_STRUCT",
              "TYPE_SIMPLEARRAY",
              "TYPE_HOMOGENEOUSARRAY",
              "TYPE_VARIANT",
              "TYPE_CSTRING",
              "TYPE_ULONG",
              "TYPE_FLAGS",
              "TYPE_HALF",
              "TYPE_STRINGPTR",
              "TYPE_RELARRAY"
            ],
            "description": "Type of the member as per hkx_types.md specification."
          },
          "vsubtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_BOOL",
              "TYPE_CHAR",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64",
              "TYPE_REAL",
              "TYPE_VECTOR4",
              "TYPE_QUATERNION",
              "TYPE_MATRIX3",
              "TYPE_ROTATION",
              "TYPE_QSTRANSFORM",
              "TYPE_MATRIX4",
              "TYPE_TRANSFORM",
              "TYPE_ZERO",
              "TYPE_POINTER",
              "TYPE_FUNCTIONPOINTER",
              "TYPE_ARRAY",
              "TYPE_INPLACEARRAY",
              "TYPE_ENUM",
              "TYPE_STRUCT",
              "TYPE_SIMPLEARRAY",
              "TYPE_HOMOGENEOUSARRAY",
              "TYPE_VARIANT",
              "TYPE_CSTRING",
              "TYPE_ULONG",
              "TYPE_FLAGS",
              "TYPE_HALF",
              "TYPE_STRINGPTR",
              "TYPE_RELARRAY",
              "TYPE_MAX"
            ],
            "description": "Subtype of the member."
          },
          "offset_x86": {
            "type": "integer",
            "description": "Offset of the member in 32-bit environment."
          },
          "offset_x86_64": {
            "type": "integer",
            "description": "Offset of the member in 64-bit environment."
          },
          "type_size_x86": {
            "type": "integer",
            "description": "Type size of the member in 32-bit environment."
          },
          "type_size_x86_64": {
            "type": "integer",
            "description": "Type size of the member in 64-bit environment."
          },
          "arrsize": {
            "type": "integer",
            "description": "Size of the array if applicable. Note: This is not used when vtype is `TYPE_ARRAY`. It is used when vtype: `TYPE_BOOL`, such as `hkBool[3]`."
          },
          "flags": {
            "type": "string",
            "description": "Flags associated with the member. e.g.(FLAGS_NONE|SERIALIZE_IGNORED)"
          },
          "default": {
            "type": "integer",
            "description": "Default value of the member."
          },
          "enum_ref": {
            "type": "string",
            "description": "Reference to an enum if the member type is enum."
          }
        },
        "required": [
          "name",
          "offset_x86",
          "offset_x86_64",
          "ctype",
          "vtype",
          "vsubtype",
          "arrsize",
          "flags",
          "default"
        ]
      },
      "description": "Members of the class."
    }
  },
  "required": [
    "name",
    "version",
    "signature",
    "size_x86",
    "size_x86_64",
    "vtable",
    "members"
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbTransformVectorModifierInternalState.json
{
  "name": "hkbTransformVectorModifierInternalState",
  "version": 0,
  "signature": "0x5ca91c99",
  "size_x86": 32,
  "size_x86_64": 32,
  "parent": "hkReferencedObject",
  "vtable": true,
  "members": [
    {
      "name": "vectorOut",
      "offset_x86": 16,
      "offset_x86_64": 16,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpVehicleFrictionStatus.json
{
  "name": "hkpVehicleFrictionStatus",
  "version": 0,
  "signature": "0x1c076a84",
  "size_x86": 72,
  "size_x86_64": 72,
  "vtable": false,
  "members": [
    {
      "name": "axis",
      "offset_x86": 0,
      "offset_x86_64": 0,
      "class_ref": "hkpVehicleFrictionStatusAxisStatus",
      "ctype": "struct hkpVehicleFrictionStatusAxisStatus[2]",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 2,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbModifierWrapper.json
{
  "name": "hkbModifierWrapper",
  "version": 0,
  "signature": "0x3697e044",
  "size_x86": 48,
  "size_x86_64": 88,
  "parent": "hkbModifier",
  "vtable": true,
  "members": [
    {
      "name": "modifier",
      "offset_x86": 44,
      "offset_x86_64": 80,
      "class_ref": "hkbModifier",
      "ctype": "struct hkbModifier*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpConvexListFilter.json
{
  "name": "hkpConvexListFilter",
  "version": 0,
  "signature": "0x81d074a4",
  "size_x86": 8,
  "size_x86_64": 16,
  "parent": "hkReferencedObject",
  "parent_has_string": false,
  "vtable": true,
  "has_string": false,
  "enums": [
    {
      "name": "ConvexListCollisionType",
      "vtype": "TYPE_ENUM",
      "vsubtype": "TYPE_VOID",
      "flags": "00000000",
      "enum_item": [
        {
          "name": "TREAT_CONVEX_LIST_AS_NORMAL",
          "value": 0
        },
        {
          "name": "TREAT_CONVEX_LIST_AS_LIST",
          "value": 1
        },
        {
          "name": "TREAT_CONVEX_LIST_AS_CONVEX",
          "value": 2
        }
      ]
    }
  ],
  "members": []
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbCharacterSetup.json
{
  "name": "hkbCharacterSetup",
  "version": 2,
  "signature": "0xe5a2a413",
  "size_x86": 48,
  "size_x86_64": 88,
  "parent": "hkReferencedObject",
  "vtable": true,
  "members": [
    {
      "name": "retargetingSkeletonMappers",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "class_ref": "hkaSkeletonMapper",
      "ctype": "hkArray<hkaSkeletonMapper*>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_POINTER",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "animationSkeleton",
      "offset_x86": 20,
      "offset_x86_64": 32,
      "class_ref": "hkaSkeleton",
      "ctype": "struct hkaSkeleton*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "ragdollToAnimationSkeletonMapper",
      "offset_x86": 24,
      "offset_x86_64": 40,
      "class_ref": "hkaSkeletonMapper",
      "ctype": "struct hkaSkeletonMapper*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "animationToRagdollSkeletonMapper",
      "offset_x86": 28,
      "offset_x86_64": 48,
      "class_ref": "hkaSkeletonMapper",
      "ctype": "struct hkaSkeletonMapper*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "animationBindingSet",
      "offset_x86": 32,
      "offset_x86_64": 56,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    },
    {
      "name": "data",
      "offset_x86": 36,
      "offset_x86_64": 64,
      "class_ref": "hkbCharacterData",
      "ctype": "struct hkbCharacterData*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "mirroredSkeleton",
      "offset_x86": 40,
      "offset_x86_64": 72,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    },
    {
      "name": "characterPropertyIdMap",
      "offset_x86": 44,
      "offset_x86_64": 80,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpPoweredChainDataConstraintInfo.json
{
  "name": "hkpPoweredChainDataConstraintInfo",
  "version": 0,
  "signature": "0xf88aee25",
  "size_x86": 80,
  "size_x86_64": 96,
  "parent_has_string": false,
  "vtable": false,
  "has_string": false,
  "members": [
    {
      "name": "pivotInA",
      "has_string": false,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "offset_x86": 0,
      "offset_x86_64": 0,
      "type_size_x86": 16,
      "type_size_x86_64": 16,
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "pivotInB",
      "has_string": false,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "offset_x86": 16,
      "offset_x86_64": 16,
      "type_size_x86": 16,
      "type_size_x86_64": 16,
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "aTc",
      "has_string": false,
      "ctype": "hkQuaternion",
      "vtype": "TYPE_QUATERNION",
      "vsubtype": "TYPE_VOID",
      "offset_x86": 32,
      "offset_x86_64": 32,
      "type_size_x86": 16,
      "type_size_x86_64": 16,
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "bTc",
      "has_string": false,
      "ctype": "hkQuaternion",
      "vtype": "TYPE_QUATERNION",
      "vsubtype": "TYPE_VOID",
      "offset_x86": 48,
      "offset_x86_64": 48,
      "type_size_x86": 16,
      "type_size_x86_64": 16,
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "motors",
      "class_ref": "hkpConstraintMotor",
      "has_string": false,
      "ctype": "struct hkpConstraintMotor*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "offset_x86": 64,
      "offset_x86_64": 64,
      "type_size_x86": 12,
      "type_size_x86_64": 24,
      "arrsize": 3,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "switchBodies",
      "has_string": false,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "offset_x86": 76,
      "offset_x86_64": 88,
      "type_size_x86": 1,
      "type_size_x86_64": 1,
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbGeneratorTransitionEffectInternalState.json
{
  "name": "hkbGeneratorTransitionEffectInternalState",
  "version": 0,
  "signature": "0xd6692b5d",
  "size_x86": 32,
  "size_x86_64": 40,
  "parent": "hkReferencedObject",
  "vtable": true,
  "members": [
    {
      "name": "timeInTransition",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "duration",
      "offset_x86": 12,
      "offset_x86_64": 20,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "effectiveBlendInDuration",
      "offset_x86": 16,
      "offset_x86_64": 24,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "effectiveBlendOutDuration",
      "offset_x86": 20,
      "offset_x86_64": 28,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "toGeneratorState",
      "offset_x86": 24,
      "offset_x86_64": 32,
      "enum_ref": "ToGeneratorState",
      "ctype": "enum ToGeneratorState",
      "vtype": "TYPE_ENUM",
      "vsubtype": "TYPE_INT8",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "echoTransitionGenerator",
      "offset_x86": 25,
      "offset_x86_64": 33,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "echoToGenerator",
      "offset_x86": 26,
      "offset_x86_64": 34,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "justActivated",
      "offset_x86": 27,
      "offset_x86_64": 35,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "updateActiveNodes",
      "offset_x86": 28,
      "offset_x86_64": 36,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "stage",
      "offset_x86": 29,
      "offset_x86_64": 37,
      "enum_ref": "Stage",
      "ctype": "enum Stage",
      "vtype": "TYPE_ENUM",
      "vsubtype": "TYPE_INT8",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpPrismaticConstraintData.json
{
  "name": "hkpPrismaticConstraintData",
  "version": 0,
  "signature": "0x3996c387",
  "size_x86": 208,
  "size_x86_64": 240,
  "parent": "hkpConstraintData",
  "vtable": true,
  "members": [
    {
      "name": "atoms",
      "offset_x86": 16,
      "offset_x86_64": 32,
      "class_ref": "hkpPrismaticConstraintDataAtoms",
      "ctype": "struct hkpPrismaticConstraintDataAtoms",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|ALIGN_16",
      "default": 0
    }
  ]
}
