=== SARDONYX-sard/serde-hkx/assets/havok_class_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Havok Class Information Schema",
  "description": "Schema for describing Havok Class Information in Json format.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the C++ class."
    },
    "parent": {
      "type": "string",
      "description": "Parent classes of the C++ class."
    },
    "parent_has_string": {
      "type": "boolean",
      "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
    },
    "version": {
      "type": "integer",
      "description": "Version of the class."
    },
    "signature": {
      "type": "string",
      "description": "Signature of the class."
    },
    "size_x86": {
      "type": "integer",
      "description": "Size of the class in 32-bit environment."
    },
    "size_x86_64": {
      "type": "integer",
      "description": "Size of the class in 64-bit environment."
    },
    "vtable": {
      "type": "boolean",
      "description": "Flag indicating if the class has a vtable."
    },
    "has_string": {
      "type": "boolean",
      "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
    },
    "enums": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the enum."
          },
          "vtype": {
            "type": "string",
            "enum": ["TYPE_ENUM", "TYPE_FLAGS"],
            "description": "Is this enum an `TYPE_ENUM` or a `TYPE_FLAGS`?"
          },
          "vsubtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64"
            ],
            "description": "The size of this enum when it is written to the binary; if it is `TYPE_VOID`, it means that the enum is not used and is unknown."
          },
          "flags": {
            "type": "string",
            "description": "Unknown flags . Always `00000000` in hk2010 version"
          },
          "enum_item": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of the enum item."
                },
                "value": {
                  "type": "integer",
                  "description": "Value of the enum item."
                }
              },
              "required": ["name", "value"]
            }
          }
        },
        "required": ["name", "vtype", "vsubtype", "flags", "enum_item"]
      },
      "description": "Enums associated with the class."
    },
    "members": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the C++ member."
          },
          "class_ref": {
            "type": "string",
            "description": "Name of the referenced class if `vtype` or `vsubtype` is `TYPE_POINTER` or `TYPE_STRUCT`."
          },
          "has_string": {
            "type": "boolean",
            "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
          },
          "ctype": {
            "type": "string",
            "description": "C data type of the member."
          },
          "vtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_BOOL",
              "TYPE_CHAR",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64",
              "TYPE_REAL",
              "TYPE_VECTOR4",
              "TYPE_QUATERNION",
              "TYPE_MATRIX3",
              "TYPE_ROTATION",
              "TYPE_QSTRANSFORM",
              "TYPE_MATRIX4",
              "TYPE_TRANSFORM",
              "TYPE_ZERO",
              "TYPE_POINTER",
              "TYPE_FUNCTIONPOINTER",
              "TYPE_ARRAY",
              "TYPE_INPLACEARRAY",
              "TYPE_ENUM",
              "TYPE_STRUCT",
              "TYPE_SIMPLEARRAY",
              "TYPE_HOMOGENEOUSARRAY",
              "TYPE_VARIANT",
              "TYPE_CSTRING",
              "TYPE_ULONG",
              "TYPE_FLAGS",
              "TYPE_HALF",
              "TYPE_STRINGPTR",
              "TYPE_RELARRAY"
            ],
            "description": "Type of the member as per hkx_types.md specification."
          },
          "vsubtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_BOOL",
              "TYPE_CHAR",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64",
              "TYPE_REAL",
              "TYPE_VECTOR4",
              "TYPE_QUATERNION",
              "TYPE_MATRIX3",
              "TYPE_ROTATION",
              "TYPE_QSTRANSFORM",
              "TYPE_MATRIX4",
              "TYPE_TRANSFORM",
              "TYPE_ZERO",
              "TYPE_POINTER",
              "TYPE_FUNCTIONPOINTER",
              "TYPE_ARRAY",
              "TYPE_INPLACEARRAY",
              "TYPE_ENUM",
              "TYPE_STRUCT",
              "TYPE_SIMPLEARRAY",
              "TYPE_HOMOGENEOUSARRAY",
              "TYPE_VARIANT",
              "TYPE_CSTRING",
              "TYPE_ULONG",
              "TYPE_FLAGS",
              "TYPE_HALF",
              "TYPE_STRINGPTR",
              "TYPE_RELARRAY",
              "TYPE_MAX"
            ],
            "description": "Subtype of the member."
          },
          "offset_x86": {
            "type": "integer",
            "description": "Offset of the member in 32-bit environment."
          },
          "offset_x86_64": {
            "type": "integer",
            "description": "Offset of the member in 64-bit environment."
          },
          "type_size_x86": {
            "type": "integer",
            "description": "Type size of the member in 32-bit environment."
          },
          "type_size_x86_64": {
            "type": "integer",
            "description": "Type size of the member in 64-bit environment."
          },
          "arrsize": {
            "type": "integer",
            "description": "Size of the array if applicable. Note: This is not used when vtype is `TYPE_ARRAY`. It is used when vtype: `TYPE_BOOL`, such as `hkBool[3]`."
          },
          "flags": {
            "type": "string",
            "description": "Flags associated with the member. e.g.(FLAGS_NONE|SERIALIZE_IGNORED)"
          },
          "default": {
            "type": "integer",
            "description": "Default value of the member."
          },
          "enum_ref": {
            "type": "string",
            "description": "Reference to an enum if the member type is enum."
          }
        },
        "required": [
          "name",
          "offset_x86",
          "offset_x86_64",
          "ctype",
          "vtype",
          "vsubtype",
          "arrsize",
          "flags",
          "default"
        ]
      },
      "description": "Members of the class."
    }
  },
  "required": [
    "name",
    "version",
    "signature",
    "size_x86",
    "size_x86_64",
    "vtable",
    "members"
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/BSIStateManagerModifier.json
{
  "name": "BSIStateManagerModifier",
  "version": 1,
  "signature": "0x6cb24f2e",
  "size_x86": 72,
  "size_x86_64": 128,
  "parent": "hkbModifier",
  "vtable": true,
  "members": [
    {
      "name": "iStateVar",
      "offset_x86": 44,
      "offset_x86_64": 80,
      "ctype": "hkInt32",
      "vtype": "TYPE_INT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "stateData",
      "offset_x86": 48,
      "offset_x86_64": 88,
      "class_ref": "BSIStateManagerModifierBSiStateData",
      "ctype": "hkArray<struct BSIStateManagerModifierBSiStateData>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "myStateListener",
      "offset_x86": 60,
      "offset_x86_64": 104,
      "class_ref": "BSIStateManagerModifierBSIStateManagerStateListener",
      "ctype": "struct BSIStateManagerModifierBSIStateManagerStateListener",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpBallSocketConstraintAtom.json
{
  "name": "hkpBallSocketConstraintAtom",
  "version": 3,
  "signature": "0xe70e4dfa",
  "size_x86": 16,
  "size_x86_64": 16,
  "parent": "hkpConstraintAtom",
  "vtable": false,
  "members": [
    {
      "name": "solvingMethod",
      "offset_x86": 2,
      "offset_x86_64": 2,
      "enum_ref": "SolvingMethod",
      "ctype": "enum SolvingMethod",
      "vtype": "TYPE_ENUM",
      "vsubtype": "TYPE_UINT8",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 1
    },
    {
      "name": "bodiesToNotify",
      "offset_x86": 3,
      "offset_x86_64": 3,
      "ctype": "hkUint8",
      "vtype": "TYPE_UINT8",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "velocityStabilizationFactor",
      "offset_x86": 4,
      "offset_x86_64": 4,
      "ctype": "hkUint8",
      "vtype": "TYPE_UINT8",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 30
    },
    {
      "name": "maxImpulse",
      "offset_x86": 8,
      "offset_x86_64": 8,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "inertiaStabilizationFactor",
      "offset_x86": 12,
      "offset_x86_64": 12,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbKeyframeBonesModifier.json
{
  "name": "hkbKeyframeBonesModifier",
  "version": 3,
  "signature": "0x95f66629",
  "size_x86": 60,
  "size_x86_64": 104,
  "parent": "hkbModifier",
  "vtable": true,
  "members": [
    {
      "name": "keyframeInfo",
      "offset_x86": 44,
      "offset_x86_64": 80,
      "class_ref": "hkbKeyframeBonesModifierKeyframeInfo",
      "ctype": "hkArray<struct hkbKeyframeBonesModifierKeyframeInfo>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "keyframedBonesList",
      "offset_x86": 56,
      "offset_x86_64": 96,
      "class_ref": "hkbBoneIndexArray",
      "ctype": "struct hkbBoneIndexArray*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbTestStateChooser.json
{
  "name": "hkbTestStateChooser",
  "version": 0,
  "signature": "0xc0fcc436",
  "size_x86": 20,
  "size_x86_64": 32,
  "parent": "hkbStateChooser",
  "vtable": true,
  "members": [
    {
      "name": "int",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "ctype": "hkInt32",
      "vtype": "TYPE_INT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "real",
      "offset_x86": 12,
      "offset_x86_64": 20,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "string",
      "offset_x86": 16,
      "offset_x86_64": 24,
      "ctype": "hkStringPtr",
      "vtype": "TYPE_STRINGPTR",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbStateMachineNestedStateMachineData.json
{
  "name": "hkbStateMachineNestedStateMachineData",
  "version": 0,
  "signature": "0x7358f5da",
  "size_x86": 8,
  "size_x86_64": 16,
  "vtable": false,
  "members": [
    {
      "name": "nestedStateMachine",
      "offset_x86": 0,
      "offset_x86_64": 0,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    },
    {
      "name": "eventIdMap",
      "offset_x86": 4,
      "offset_x86_64": 8,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpCachingShapePhantom.json
{
  "name": "hkpCachingShapePhantom",
  "version": 0,
  "signature": "0xcf227f58",
  "size_x86": 368,
  "size_x86_64": 448,
  "parent": "hkpShapePhantom",
  "vtable": true,
  "members": [
    {
      "name": "collisionDetails",
      "offset_x86": 352,
      "offset_x86_64": 416,
      "ctype": "hkArray<void>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    },
    {
      "name": "orderDirty",
      "offset_x86": 364,
      "offset_x86_64": 432,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/BSIStateManagerModifierBSIStateManagerStateListener.json
{
  "name": "BSIStateManagerModifierBSIStateManagerStateListener",
  "version": 0,
  "signature": "0x99463586",
  "size_x86": 12,
  "size_x86_64": 24,
  "parent": "hkbStateListener",
  "vtable": true,
  "members": [
    {
      "name": "pStateManager",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbFootIkControlsModifierLeg.json
{
  "name": "hkbFootIkControlsModifierLeg",
  "version": 0,
  "signature": "0x9e17091a",
  "size_x86": 32,
  "size_x86_64": 48,
  "vtable": false,
  "members": [
    {
      "name": "groundPosition",
      "offset_x86": 0,
      "offset_x86_64": 0,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "ungroundedEvent",
      "offset_x86": 16,
      "offset_x86_64": 16,
      "class_ref": "hkbEventProperty",
      "ctype": "struct hkbEventProperty",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "verticalError",
      "offset_x86": 24,
      "offset_x86_64": 32,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "hitSomething",
      "offset_x86": 28,
      "offset_x86_64": 36,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "isPlantedMS",
      "offset_x86": 29,
      "offset_x86_64": 37,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}
