=== SARDONYX-sard/serde-hkx/assets/havok_class_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Havok Class Information Schema",
  "description": "Schema for describing Havok Class Information in Json format.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the C++ class."
    },
    "parent": {
      "type": "string",
      "description": "Parent classes of the C++ class."
    },
    "parent_has_string": {
      "type": "boolean",
      "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
    },
    "version": {
      "type": "integer",
      "description": "Version of the class."
    },
    "signature": {
      "type": "string",
      "description": "Signature of the class."
    },
    "size_x86": {
      "type": "integer",
      "description": "Size of the class in 32-bit environment."
    },
    "size_x86_64": {
      "type": "integer",
      "description": "Size of the class in 64-bit environment."
    },
    "vtable": {
      "type": "boolean",
      "description": "Flag indicating if the class has a vtable."
    },
    "has_string": {
      "type": "boolean",
      "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
    },
    "enums": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the enum."
          },
          "vtype": {
            "type": "string",
            "enum": ["TYPE_ENUM", "TYPE_FLAGS"],
            "description": "Is this enum an `TYPE_ENUM` or a `TYPE_FLAGS`?"
          },
          "vsubtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64"
            ],
            "description": "The size of this enum when it is written to the binary; if it is `TYPE_VOID`, it means that the enum is not used and is unknown."
          },
          "flags": {
            "type": "string",
            "description": "Unknown flags . Always `00000000` in hk2010 version"
          },
          "enum_item": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of the enum item."
                },
                "value": {
                  "type": "integer",
                  "description": "Value of the enum item."
                }
              },
              "required": ["name", "value"]
            }
          }
        },
        "required": ["name", "vtype", "vsubtype", "flags", "enum_item"]
      },
      "description": "Enums associated with the class."
    },
    "members": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the C++ member."
          },
          "class_ref": {
            "type": "string",
            "description": "Name of the referenced class if `vtype` or `vsubtype` is `TYPE_POINTER` or `TYPE_STRUCT`."
          },
          "has_string": {
            "type": "boolean",
            "description": "Type or subtype is `CString` or `StringPtr`, or `struct containing them` type?(To calculate lifetime)"
          },
          "ctype": {
            "type": "string",
            "description": "C data type of the member."
          },
          "vtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_BOOL",
              "TYPE_CHAR",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64",
              "TYPE_REAL",
              "TYPE_VECTOR4",
              "TYPE_QUATERNION",
              "TYPE_MATRIX3",
              "TYPE_ROTATION",
              "TYPE_QSTRANSFORM",
              "TYPE_MATRIX4",
              "TYPE_TRANSFORM",
              "TYPE_ZERO",
              "TYPE_POINTER",
              "TYPE_FUNCTIONPOINTER",
              "TYPE_ARRAY",
              "TYPE_INPLACEARRAY",
              "TYPE_ENUM",
              "TYPE_STRUCT",
              "TYPE_SIMPLEARRAY",
              "TYPE_HOMOGENEOUSARRAY",
              "TYPE_VARIANT",
              "TYPE_CSTRING",
              "TYPE_ULONG",
              "TYPE_FLAGS",
              "TYPE_HALF",
              "TYPE_STRINGPTR",
              "TYPE_RELARRAY"
            ],
            "description": "Type of the member as per hkx_types.md specification."
          },
          "vsubtype": {
            "type": "string",
            "enum": [
              "TYPE_VOID",
              "TYPE_BOOL",
              "TYPE_CHAR",
              "TYPE_INT8",
              "TYPE_UINT8",
              "TYPE_INT16",
              "TYPE_UINT16",
              "TYPE_INT32",
              "TYPE_UINT32",
              "TYPE_INT64",
              "TYPE_UINT64",
              "TYPE_REAL",
              "TYPE_VECTOR4",
              "TYPE_QUATERNION",
              "TYPE_MATRIX3",
              "TYPE_ROTATION",
              "TYPE_QSTRANSFORM",
              "TYPE_MATRIX4",
              "TYPE_TRANSFORM",
              "TYPE_ZERO",
              "TYPE_POINTER",
              "TYPE_FUNCTIONPOINTER",
              "TYPE_ARRAY",
              "TYPE_INPLACEARRAY",
              "TYPE_ENUM",
              "TYPE_STRUCT",
              "TYPE_SIMPLEARRAY",
              "TYPE_HOMOGENEOUSARRAY",
              "TYPE_VARIANT",
              "TYPE_CSTRING",
              "TYPE_ULONG",
              "TYPE_FLAGS",
              "TYPE_HALF",
              "TYPE_STRINGPTR",
              "TYPE_RELARRAY",
              "TYPE_MAX"
            ],
            "description": "Subtype of the member."
          },
          "offset_x86": {
            "type": "integer",
            "description": "Offset of the member in 32-bit environment."
          },
          "offset_x86_64": {
            "type": "integer",
            "description": "Offset of the member in 64-bit environment."
          },
          "type_size_x86": {
            "type": "integer",
            "description": "Type size of the member in 32-bit environment."
          },
          "type_size_x86_64": {
            "type": "integer",
            "description": "Type size of the member in 64-bit environment."
          },
          "arrsize": {
            "type": "integer",
            "description": "Size of the array if applicable. Note: This is not used when vtype is `TYPE_ARRAY`. It is used when vtype: `TYPE_BOOL`, such as `hkBool[3]`."
          },
          "flags": {
            "type": "string",
            "description": "Flags associated with the member. e.g.(FLAGS_NONE|SERIALIZE_IGNORED)"
          },
          "default": {
            "type": "integer",
            "description": "Default value of the member."
          },
          "enum_ref": {
            "type": "string",
            "description": "Reference to an enum if the member type is enum."
          }
        },
        "required": [
          "name",
          "offset_x86",
          "offset_x86_64",
          "ctype",
          "vtype",
          "vsubtype",
          "arrsize",
          "flags",
          "default"
        ]
      },
      "description": "Members of the class."
    }
  },
  "required": [
    "name",
    "version",
    "signature",
    "size_x86",
    "size_x86_64",
    "vtable",
    "members"
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpVehicleDefaultAerodynamics.json
{
  "name": "hkpVehicleDefaultAerodynamics",
  "version": 0,
  "signature": "0x42fc5bbd",
  "size_x86": 48,
  "size_x86_64": 48,
  "parent": "hkpVehicleAerodynamics",
  "vtable": true,
  "members": [
    {
      "name": "airDensity",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "frontalArea",
      "offset_x86": 12,
      "offset_x86_64": 20,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "dragCoefficient",
      "offset_x86": 16,
      "offset_x86_64": 24,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "liftCoefficient",
      "offset_x86": 20,
      "offset_x86_64": 28,
      "ctype": "hkReal",
      "vtype": "TYPE_REAL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "extraGravityws",
      "offset_x86": 32,
      "offset_x86_64": 32,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkaWaveletCompressedAnimation.json
{
  "name": "hkaWaveletCompressedAnimation",
  "version": 0,
  "signature": "0x77cf0962",
  "size_x86": 112,
  "size_x86_64": 136,
  "parent": "hkaAnimation",
  "vtable": true,
  "members": [
    {
      "name": "numberOfPoses",
      "offset_x86": 40,
      "offset_x86_64": 56,
      "ctype": "hkInt32",
      "vtype": "TYPE_INT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "blockSize",
      "offset_x86": 44,
      "offset_x86_64": 60,
      "ctype": "hkInt32",
      "vtype": "TYPE_INT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "qFormat",
      "offset_x86": 48,
      "offset_x86_64": 64,
      "class_ref": "hkaWaveletCompressedAnimationQuantizationFormat",
      "ctype": "struct hkaWaveletCompressedAnimationQuantizationFormat",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "staticMaskIdx",
      "offset_x86": 68,
      "offset_x86_64": 84,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "staticDOFsIdx",
      "offset_x86": 72,
      "offset_x86_64": 88,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "numStaticTransformDOFs",
      "offset_x86": 76,
      "offset_x86_64": 92,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "numDynamicTransformDOFs",
      "offset_x86": 80,
      "offset_x86_64": 96,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "blockIndexIdx",
      "offset_x86": 84,
      "offset_x86_64": 100,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "blockIndexSize",
      "offset_x86": 88,
      "offset_x86_64": 104,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "quantizedDataIdx",
      "offset_x86": 92,
      "offset_x86_64": 108,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "quantizedDataSize",
      "offset_x86": 96,
      "offset_x86_64": 112,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "dataBuffer",
      "offset_x86": 100,
      "offset_x86_64": 120,
      "ctype": "hkArray<hkUint8>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_UINT8",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbFootIkControlsModifier.json
{
  "name": "hkbFootIkControlsModifier",
  "version": 1,
  "signature": "0xe5b6f544",
  "size_x86": 144,
  "size_x86_64": 176,
  "parent": "hkbModifier",
  "vtable": true,
  "members": [
    {
      "name": "controlData",
      "offset_x86": 48,
      "offset_x86_64": 80,
      "class_ref": "hkbFootIkControlData",
      "ctype": "struct hkbFootIkControlData",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "legs",
      "offset_x86": 96,
      "offset_x86_64": 128,
      "class_ref": "hkbFootIkControlsModifierLeg",
      "ctype": "hkArray<struct hkbFootIkControlsModifierLeg>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "errorOutTranslation",
      "offset_x86": 112,
      "offset_x86_64": 144,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "alignWithGroundRotation",
      "offset_x86": 128,
      "offset_x86_64": 160,
      "ctype": "hkQuaternion",
      "vtype": "TYPE_QUATERNION",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpDefaultWorldMemoryWatchDog.json
{
  "name": "hkpDefaultWorldMemoryWatchDog",
  "version": 1,
  "signature": "0x77d6b19f",
  "size_x86": 12,
  "size_x86_64": 24,
  "parent": "hkWorldMemoryAvailableWatchDog",
  "vtable": true,
  "members": [
    {
      "name": "freeHeapMemoryRequested",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "ctype": "hkInt32",
      "vtype": "TYPE_INT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbFootIkModifierInternalLegData.json
{
  "name": "hkbFootIkModifierInternalLegData",
  "version": 1,
  "signature": "0xe5ca3677",
  "size_x86": 32,
  "size_x86_64": 32,
  "vtable": false,
  "members": [
    {
      "name": "groundPosition",
      "offset_x86": 0,
      "offset_x86_64": 0,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "footIkSolver",
      "offset_x86": 16,
      "offset_x86_64": 16,
      "ctype": "void*",
      "vtype": "TYPE_POINTER",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE|SERIALIZE_IGNORED",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkbSetWordVariableCommand.json
{
  "name": "hkbSetWordVariableCommand",
  "version": 0,
  "signature": "0xf3ae5fca",
  "size_x86": 64,
  "size_x86_64": 64,
  "parent": "hkReferencedObject",
  "vtable": true,
  "members": [
    {
      "name": "quadValue",
      "offset_x86": 16,
      "offset_x86_64": 16,
      "ctype": "hkVector4",
      "vtype": "TYPE_VECTOR4",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "characterId",
      "offset_x86": 32,
      "offset_x86_64": 32,
      "ctype": "hkUint64",
      "vtype": "TYPE_UINT64",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "variableId",
      "offset_x86": 40,
      "offset_x86_64": 40,
      "ctype": "hkInt32",
      "vtype": "TYPE_INT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "value",
      "offset_x86": 44,
      "offset_x86_64": 44,
      "class_ref": "hkbVariableValue",
      "ctype": "struct hkbVariableValue",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "type",
      "offset_x86": 48,
      "offset_x86_64": 48,
      "enum_ref": "VariableType",
      "ctype": "enum VariableType",
      "vtype": "TYPE_ENUM",
      "vsubtype": "TYPE_UINT8",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "global",
      "offset_x86": 49,
      "offset_x86_64": 49,
      "ctype": "hkBool",
      "vtype": "TYPE_BOOL",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkpShapePhantom.json
{
  "name": "hkpShapePhantom",
  "version": 0,
  "signature": "0xcb22fbcd",
  "size_x86": 352,
  "size_x86_64": 416,
  "parent": "hkpPhantom",
  "vtable": true,
  "members": [
    {
      "name": "motionState",
      "offset_x86": 176,
      "offset_x86_64": 240,
      "class_ref": "hkMotionState",
      "ctype": "struct hkMotionState",
      "vtype": "TYPE_STRUCT",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}

=== SARDONYX-sard/serde-hkx/assets/classes/hkMonitorStreamColorTable.json
{
  "name": "hkMonitorStreamColorTable",
  "version": 0,
  "signature": "0x79e53e85",
  "size_x86": 24,
  "size_x86_64": 40,
  "parent": "hkReferencedObject",
  "vtable": true,
  "members": [
    {
      "name": "colorPairs",
      "offset_x86": 8,
      "offset_x86_64": 16,
      "class_ref": "hkMonitorStreamColorTableColorPair",
      "ctype": "hkArray<struct hkMonitorStreamColorTableColorPair>",
      "vtype": "TYPE_ARRAY",
      "vsubtype": "TYPE_STRUCT",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    },
    {
      "name": "defaultColor",
      "offset_x86": 20,
      "offset_x86_64": 32,
      "ctype": "hkUint32",
      "vtype": "TYPE_UINT32",
      "vsubtype": "TYPE_VOID",
      "arrsize": 0,
      "flags": "FLAGS_NONE",
      "default": 0
    }
  ]
}
